In [14]:
list(range(0,11,2))

[0, 2, 4, 6, 8, 10]

In [15]:
import numpy as np

In [10]:
my_mat = [[1,2,4], [4,5,6],[7,8,9]]

In [12]:
my_mat

[[1, 2, 4], [4, 5, 6], [7, 8, 9]]

In [17]:
np.array(my_mat)

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones(4)

array([1., 1., 1., 1.])

In [38]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

TypeError: data type not understood

In [31]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [34]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.random.rand(5)

array([0.3140868 , 0.6373116 , 0.87982846, 0.58464906, 0.61416115])

# unlike the np.array need be passed in a tuple to create a two demensional list,
# np.random.rand only needs sencond arguement

In [2]:
np.random.rand(5,5)

NameError: name 'np' is not defined

In [43]:
np.random.randn(4,4)

array([[-0.36950707, -0.09801266,  0.65937748, -0.21563066],
       [-0.09560207,  1.12279857,  1.44923519,  0.34301844],
       [-0.82819967, -0.44624136, -0.798641  ,  0.30799896],
       [ 0.11247509,  1.06583766,  0.206271  , -0.54158725]])

In [47]:
np.random.randint(1,100,10)

array([ 9, 90, 22, 67, 38, 48, 31,  1, 29,  8])

In [50]:
arr = np.arange(25)

In [3]:
arr

NameError: name 'arr' is not defined

In [4]:
arr.shape

NameError: name 'arr' is not defined

In [55]:
ranarr = np.random.randint(0,50,10)

In [57]:
ranarr

array([38, 17, 41, 49, 34,  7, 12, 19, 24, 14])

In [60]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
arr2 = np.arange(5,10,2)

In [70]:
arr2

array([5, 7, 9])

In [73]:
ranarr.max()

49

In [76]:
ranarr.min()

7

In [79]:
ranarr.argmax()

3

In [81]:
ranarr.argmin()

5

In [85]:
arr = arr.reshape(5,5)

In [87]:
arr.shape

(5, 5)

In [89]:
arr.dtype

dtype('int32')

In [91]:
from numpy.random import randint 

In [94]:
randint(2,10,3)

array([6, 6, 8])